#!/bin/bash

# QA System Deployment Checklist and Test Script
# This script helps you deploy and verify the QA system

echo "🚀 QA System Deployment Checklist"
echo "=================================="

echo ""
echo "📋 Pre-Deployment Checklist:"
echo "1. ✅ QA endpoints created (api/qa/*)"
echo "2. ✅ Admin UI created (api/admin/qa.js)"
echo "3. ✅ GitHub Actions workflow created (.github/workflows/post-deploy-qa.yml)"
echo "4. ✅ Database schema ready (qa-runs-schema.sql)"
echo "5. ✅ QA helper functions created (api/lib/qa-*)"
echo ""

echo "🔧 Deployment Steps:"
echo "1. Run the database schema:"
echo "   - Execute qa-runs-schema.sql in your Supabase dashboard"
echo "   - Or use: psql -f qa-runs-schema.sql"
echo ""

echo "2. Set environment variables:"
echo "   - Add QA_SECRET to your Vercel environment variables"
echo "   - Add QA_SECRET to your GitHub repository secrets"
echo ""

echo "3. Deploy to production:"
echo "   - Push to main branch or deploy via Vercel"
echo "   - Wait for deployment to complete"
echo ""

echo "4. Test the deployment:"
echo "   - Run: ./scripts/qa-system-test.sh"
echo "   - Or manually test each endpoint"
echo ""

echo "🧪 Manual Testing Commands:"
echo "=========================="
echo ""
echo "# Set your QA secret"
echo "export QA_SECRET='your-secret-here'"
echo ""
echo "# Test individual endpoints"
echo "curl -s -X POST 'https://theflowstateapp.com/api/qa/reset?secret=\$QA_SECRET' | jq"
echo "curl -s -X POST 'https://theflowstateapp.com/api/qa/seed?secret=\$QA_SECRET' | jq"
echo "curl -s -X POST 'https://theflowstateapp.com/api/qa/run?secret=\$QA_SECRET' | jq"
echo "curl -s 'https://theflowstateapp.com/api/qa/latest' | jq"
echo "curl -s 'https://theflowstateapp.com/api/qa/history' | jq"
echo ""
echo "# Test admin panel"
echo "open https://theflowstateapp.com/api/admin/qa"
echo ""

echo "📊 Expected Results After Deployment:"
echo "====================================="
echo "✅ QA Reset: Returns { ok: true, deleted: {...} }"
echo "✅ QA Seed: Returns { ok: true, workspaceId: 'qa-ws', counts: {...} }"
echo "✅ QA Run: Returns { ok: true, saved: true, report: {...} }"
echo "✅ QA Latest: Returns { ok: true/false, ts: '...', failing_steps: [...] }"
echo "✅ QA History: Returns array of recent runs"
echo "✅ Admin Panel: Shows HTML page with QA status table"
echo ""

echo "🔍 Troubleshooting:"
echo "==================="
echo "If endpoints return 404:"
echo "- Check that files are deployed to api/qa/ and api/admin/"
echo "- Verify Vercel deployment completed successfully"
echo "- Check Vercel function logs for errors"
echo ""
echo "If endpoints return 403:"
echo "- Verify QA_SECRET is set correctly"
echo "- Check that secret matches between environment and request"
echo ""
echo "If database errors occur:"
echo "- Verify qa_runs table exists in Supabase"
echo "- Check RLS policies are configured correctly"
echo "- Verify SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set"
echo ""

echo "🎯 Next Steps After Successful Deployment:"
echo "==========================================="
echo "1. Run comprehensive test: ./scripts/qa-system-test.sh"
echo "2. Check admin panel: https://theflowstateapp.com/api/admin/qa"
echo "3. Test GitHub Actions by pushing to main branch"
echo "4. Integrate QA banner into your app using api/lib/qa-integration-example.js"
echo "5. Monitor QA runs in production"
echo ""

echo "📝 Files Created:"
echo "================="
echo "✅ api/qa/reset.js - Reset test data"
echo "✅ api/qa/seed.js - Seed test data"
echo "✅ api/qa/smoke.js - Run smoke test"
echo "✅ api/qa/run.js - Run and store results"
echo "✅ api/qa/latest.js - Get latest status"
echo "✅ api/qa/history.js - Get run history"
echo "✅ api/admin/qa.js - Admin UI"
echo "✅ api/lib/qa-auth.js - Authentication helper"
echo "✅ api/lib/qa-smoke.js - Smoke test logic"
echo "✅ api/lib/qa-banner.js - App banner helper"
echo "✅ api/lib/qa-integration-example.js - Integration examples"
echo "✅ .github/workflows/post-deploy-qa.yml - GitHub Actions"
echo "✅ qa-runs-schema.sql - Database schema"
echo "✅ scripts/qa-system-test.sh - Test script"
echo "✅ scripts/qa-verify.sh - Verification script"
echo ""

echo "🎉 QA System is ready for deployment!"
echo "Follow the steps above to deploy and test the system."
